#+TITLE: Gestione di veicoli autonomi agli incroci
#+SETUPFILE: ./latex-theme.setup
#+AUTHOR: Matteo Lugli
#+DATE: 
#+OPTIONS: num:2
\newpage
* Introduzione
La guida autonoma nei prossimi anni diventerà progressivamente parte
integrante della nostra vita, sostituendo una delle attività umane 
tra le più stressanti e pericolose. 
Soltanto nel 2021 in Italia sono stati registrati più di 150 mila incidenti
stradali che hanno provocato circa 3000 morti e 200 mila feriti.
Il ruolo principale della tecnologia è quello di creare soluzioni che mettano
l'esperienza dell'uomo al centro, cercando di facilitare, migliorare e rendere 
più sicure le attività quotidiane.
A tal proposito la ricerca si è evoluta molto rapidamente negli ultimi anni,
proponendosi di trasformare radicalmente il modo in cui guidiamo.
La Society of Automotive Engineers (SAE) descrive il coinvolgimento umano alla guida tramite
una classifica basata su 5 livelli:
+ Livello 0 \newline
  Nessuna automazione: le auto non presentano dispositivi automatici in grado di dare
  assistenza attiva al guidatore, che deve sempre mantenere il pieno controllo del veicolo.
  Sono ricondotte a questo livello anche automobili equipaggiate con sistemi di frenata di 
  emergenza o di rilevazione di collisioni imminenti.
+ Livello 1 \newline
  Assistenza alla guida: il veicolo è dotato di sistemi come l'assistenza al mantenimento della
  corsia (LKA) o il controllo di velocità adattivo (ACC). Il conducente è comumque pienamente
  responsabile della guida, mantenendo il controllo del veicolo.
+ Livello 2 \newline
  Automazione parziale alla guida: i veicoli sono equipaggiati con sistemi ADAS (/Advanced Driver Assistance Systems/)
  che in certe situazioni possono aiutare attivamente il conducente con il controllo dello sterzo, l'accellerazione
  e la frenata. /Autopilot/ di /Tesla/, che ad oggi viene continuamente aggiornato tramite
  l'aggiunta di nuove funzionalità di assistenza alla guida, è ancora classificato come livello 2.
+ Livello 3 \newline
  Automazione condizionata: il veicolo è in grado di gestire autonomamente la guida in
  strada. Per legge, il conducente deve comunque essere sempre abilitato a poter mettere
  le mani sul volante e prendere il controllo dell'auto. Alcune compagnie
  come /Honda/ hanno rilasciato sul mercato automobili di livello 3 considerabili
  completamente autonome in alcune zone urbane del giappone o sulle autostrade.
+ Livello 4 \newline
  Automazione elevata: il veicolo è completamente autonomo nella guida e nella navigazione.
  Nonostante sia comunque necessaria la presenza di un conducente, il suo intervento
  non dovrebbe essere mai richiesto. Anche questi sistemi sono tipicamente funzionanti
  soltanto in certe aree geografiche.
+ Livello 5 \newline
  Automazione completa: il veicolo è autonomo in qualsiasi condizione, e non è necessaria
  la presenza di un passeggero a bordo.    

La guida in strada è un argomento 

** Contributo di questa tesi
Questa tesi vuole esplorare ulteriori possibilità offerte dagli algoritmi
di coordinamento di veicoli autonomi agli incroci basati sulle aste.
In particolare, vengono proposte alcune estensioni dell'algoritmo
cooperativo spiegato in [paper gherardini] per cercare di migliorare
/(i)/ il /throughput/ dell'incrocio e /(ii)/ il tempo di attesa nel 
traffico dei veicoli tramite una migliore gestione indiretta delle situazioni
di congestione.
Si è poi proposto un algoritmo basato sul /Deep Q-Learning/[paper deepmind]
in grado di allenare i manager degli incroci basandosi soltanto sull'esperienza
passata, senza avere a disposizione dati di partenza.
In particolare, si è voluto verificare che l'overhead dato dalla presenza di 
un complesso meccanismo economico basato sulle aste fosse realmente necessario per mantenere
la /fairness/ dell'incrocio.
\newpage
* Algoritmo
** Stato dell'arte
La maggior parte della letteratura si pone in uno scenario in cui 
le strade sono popolate totalmente da veicoli a guida autonoma,
in grado di comunicare tra di loro (/Vehicle to Vehicle comunication/, o V2V)
e con dispositivi installati in prossimità degli incroci
(/Vehicle to Infrastructure comunication/ o V2I).
Nonostante i progressi, si è ancora ben lontani dal vedere solo veicoli
autonomi dominare le nostre strade. Il cambiamento dell'attuale paradigma
di guida avverrà nel corso di molti anni, periodo in cui si dovranno gestire
sia veicoli autonomi che veicoli non attrezzati (massimo di livello 2).

I metodi di valutazione principali usati in letteratura per confrontare
l'efficacia di diversi algoritmi sono i seguenti:
+ tempo di attesa nel traffico, o /waiting time/: rappresenta il tempo
  in cui il veicolo è costretto ad aspettare in coda;
+ tempo di attesa all'incrocio, o /crossroad waiting time/: è il tempo
  speso dal veicolo in prossimità dell'incrocio, aspettando il suo turno
  di attraversamento;
+ bilanciamento del metodo, o /fairness/: si riferisce al principio 
  di gestire tutti i veicoli nel modo più equo possibile, in base
  alle esigenze di ognuno.

Secondo gli esperimenti riportati in [paper g] la variante dell'algoritmo
/Auction Based/ (AB) più performante in termini di tempi di attesa nel traffico
e di bilanciamento  ( /fairness/ ) è quella cooperativa, che prevede l'attraversamento
dell'incrocio di tutti i veicoli che hanno partecipato all'asta. In particolare
ogni veicolo effettua una puntata prelevando "denaro" (una generica valuta) 
dal suo portafoglio virtuale, inviandola al manager dell'incrocio. Quest'ultimo
raccoglie tutte le puntate dei veicoli partecipanti, per poi determinare
l'ordine di attraversamento partendo dall'autore della puntata più alta, ossia il vincitore dell'asta.
Secondo il modello competitivo è soltanto il vincitore ad attraversare
l'incrocio: gli altri parteciperanno all'asta successiva.
Sono stati proposti diversi metodi per gestire il pagamento finale: secondo
quello che si è rivelato essere più equilibrato è soltanto il vincitore a pagare
la puntata (/only winner pays/).
In [pg] l'/ehnancement/ viene applicato per permettere anche alle auto
che aspettano in coda di partecipare indirettamente all'asta: per ogni auto
che aspetta in coda dietro all'attuale veicolo che sta partecipando viene aggiunto
un piccolo contributo positivo alla puntata di quest'ultimo, secondo la formula (1).
Nonostante questa modifica migliori nel complesso i tempi di attesa e la /fairness/, 
permane il problema che il sistema di aste determina soltanto l'ordine di attraversamento dei veicoli,
senza considerare le situazioni di congestione del traffico.
Tramite la variante proposta in questa tesi vengono migliorati /(i)/ la /fairness/ nel complesso,
/(ii)/ il tempo medio di attesa nel traffico e /(iii)/ il tempo di attesa
all'incrocio.



# \begin{algorithm}
# \caption{Algoritmo ad asta ibrida}\label{alg:cap}
# \begin{algorithmic}
# \Require $n \geq 0$
# \Ensure $y = x^n$
# \State $y \gets 1$
# \State $X \gets x$
# \State $N \gets n$
# \While{$N \neq 0$}
# \If{$N$ is even}
#     \State $X \gets X \times X$
#     \State $N \gets \frac{N}{2}$  \Comment{This is a comment}
# \ElsIf{$N$ is odd}
#     \State $y \gets y \times X$
#     \State $N \gets N - 1$
# \EndIf
# \EndWhile
# \end{algorithmic}
# \end{algorithm}
** Algoritmo ibrido
La variante proposta prende il nome di algoritmo di coordinamento
ibrido, ispirandosi sia al modello cooperativo che 
dal competitivo.
\begin{algorithm}
\caption{Hybrid manager}\label{alg:cap}
\begin{algorithmic}
\State $C$ = veicoli partecipanti all'asta
\State $W$ = lista ordinata di veicoli vincitori dell'asta
\State $\gamma$ = lunghezza massima della lista $W$
\For{$v$ in $W$}
\State $F$ = [v]
  \For{$f$ in $C$}
    \For{$c$ in $F$}
      \If{$f$.direction !intersect with $c$.direction}
        \State $F$.append(f)
      \EndIf
    \EndFor
  \EndFor
\State F.depart()
\EndFor
\end{algorithmic}
\end{algorithm}

Secondo gli esperimenti, il valore ottimale del parametro $\gamma$
è $2$. Ciò significa che di tutti i veicoli che hanno partecipato all'asta
soltanto due di questi attraverseranno sicuramente l'incrocio, dando però
la possibilità ad altri veicoli con traiettorie che non collidono di attraversare
l'incrocio nello stesso momento. In questo modo si cerca di massimizzare il /throughput/
dell'incrocio ad ogni asta, mantenendo comunque un alto livello di sicurezza rispetto
alle collisioni.
