model: Coop
CP: owp
MCA: 1
E: y
Spn: 10
betaL: 0.05
betaU: 0.15
betaR: 0.1
Bdn: b
Rts: f
Stp: 10000
VS: 120
RUNS: 1
TV: 74
UB: 7
beta: 0.1
train: False
load: True
name: booster
alpha: 0.3
TF: 10
UF: 10
MV: hope
EXE: 1
EVE: 0
BS: 32
G: 0.3
